In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [34]:
np.random.seed(42)
X = np.random.rand(100, 1) - 0.5
y = 3*X[:, 0]**2 + 0.05 * np.random.randn(100)

In [35]:
df = pd.DataFrame()

df['X'] = X.reshape(100)
df['y'] = y

df

           X         y
0  -0.125460  0.051573
1   0.450714  0.594480
2   0.231994  0.166052
3   0.098658 -0.070178
4  -0.343981  0.343986
..       ...       ...
95 -0.006204 -0.040675
96  0.022733 -0.002305
97 -0.072459  0.032809
98 -0.474581  0.689516
99 -0.392109  0.502607

[100 rows x 2 columns]

In [36]:
df["pred"] = df["y"].mean()
df["Residual"] = df["y"] - df["pred"]

df

           X         y      pred  Residual
0  -0.125460  0.051573  0.265458 -0.213885
1   0.450714  0.594480  0.265458  0.329021
2   0.231994  0.166052  0.265458 -0.099407
3   0.098658 -0.070178  0.265458 -0.335636
4  -0.343981  0.343986  0.265458  0.078528
..       ...       ...       ...       ...
95 -0.006204 -0.040675  0.265458 -0.306133
96  0.022733 -0.002305  0.265458 -0.267763
97 -0.072459  0.032809  0.265458 -0.232650
98 -0.474581  0.689516  0.265458  0.424057
99 -0.392109  0.502607  0.265458  0.237148

[100 rows x 4 columns]

In [32]:
# here we asking the model to predict amount of error it is doing
for i in range(0, 100):
    model = DecisionTreeRegressor()
    model.fit(df[["X"]], df[["Residual"]])
    df["pred"] = df["pred"] + 0.1*model.predict(df[["X"]])
    
    df["Residual"] = df["y"] -  df["pred"]

In [28]:
# y = m1 + m2*lr + m3*lr

In [33]:
df

           X         y      pred  Residual
0  -0.125460  0.051573  0.051579 -0.000006
1   0.450714  0.594480  0.594471  0.000009
2   0.231994  0.166052  0.166054 -0.000003
3   0.098658 -0.070178 -0.070169 -0.000009
4  -0.343981  0.343986  0.343984  0.000002
..       ...       ...       ...       ...
95 -0.006204 -0.040675 -0.040667 -0.000008
96  0.022733 -0.002305 -0.002298 -0.000007
97 -0.072459  0.032809  0.032815 -0.000006
98 -0.474581  0.689516  0.689504  0.000011
99 -0.392109  0.502607  0.502600  0.000006

[100 rows x 4 columns]

In [37]:
df

           X         y      pred  Residual
0  -0.125460  0.051573  0.265458 -0.213885
1   0.450714  0.594480  0.265458  0.329021
2   0.231994  0.166052  0.265458 -0.099407
3   0.098658 -0.070178  0.265458 -0.335636
4  -0.343981  0.343986  0.265458  0.078528
..       ...       ...       ...       ...
95 -0.006204 -0.040675  0.265458 -0.306133
96  0.022733 -0.002305  0.265458 -0.267763
97 -0.072459  0.032809  0.265458 -0.232650
98 -0.474581  0.689516  0.265458  0.424057
99 -0.392109  0.502607  0.265458  0.237148

[100 rows x 4 columns]

In [ ]:
# 2nd model 
model = DecisionTreeRegressor()
model.fit(df[["X"]], df[["Residual"]])  # Input = Input Features, Output =error done by previous model in predicting the value. 
 
df["pred"] = df["pred"] + 0.1 * model.predict(df[["X"]])  # Learning Rate = 0.1
    
df["Residual"] = df["y"] -  df["pred"]        # Actual - Predicted